#include <pebble.h>
#include <pebble_fonts.h>

static Window *window;
static TextLayer *text_layer;
static TextLayer *time_layer;
static GBitmap* button_bitmap;
static BitmapLayer* button_labels;
static bool timer_running=false;
static time_t start_time_s = 0;
static uint16_t start_time_ms = 0;
static double start_time = 0; 
static AppTimer* my_timer;
static GFont my_font;
static void timer_handler ();

static void select_click_handler(ClickRecognizerRef recognizer, void *context) {
  uint16_t now_ms;
  if (timer_running) {
	timer_running=false;}
  else {
	timer_running=true;
	if (start_time==0) {
		start_time_ms=time_ms(&start_time_s, NULL);
		start_time = (double)start_time_s + ((double)start_time_ms/1000);
	};
	// If I'm restarting, I need to sync the timer loop to the original start time
	now_ms=time_ms(NULL, NULL);	
	my_timer = app_timer_register((1000+now_ms-start_time_ms)%100, timer_handler, NULL);
  };
}

static void update_display() {
  time_t now_s;
  uint16_t now_ms;
  double now;  
  double elapsed_time;
  now_ms=time_ms(&now_s, NULL);
  now=(double)now_s+((double)now_ms/1000) ;
  if (start_time==0) {
	elapsed_time=0;}
  else {elapsed_time = now - start_time;};
  int tenths = (int)(elapsed_time * 10) % 10;
  int seconds = (int)elapsed_time % 60;
  int minutes = (int)elapsed_time / 60 % 60;
  static char display_time[] = "00:00.0";  
  snprintf(display_time, 8, "%02d:%02d.%1d", minutes, seconds, tenths);
  text_layer_set_text (time_layer, display_time);

 }

static void up_click_handler(ClickRecognizerRef recognizer, void *context) {
  start_time=0;
  timer_running=false;
  text_layer_set_text (time_layer, "00:00.0");
  update_display();
}

static void down_click_handler(ClickRecognizerRef recognizer, void *context) {
  ;
}

static void click_config_provider(void *context) {
  window_single_click_subscribe(BUTTON_ID_SELECT, select_click_handler);
  window_single_click_subscribe(BUTTON_ID_UP, up_click_handler);
  window_single_click_subscribe(BUTTON_ID_DOWN, down_click_handler);
}

static void timer_handler () {
  if(timer_running) {
	my_timer = app_timer_register(100, timer_handler, NULL);
        update_display();
  }
}

static void window_load(Window *window) {
/* Code generated by create-project
  Layer *window_layer = window_get_root_layer(window);
  GRect bounds = layer_get_bounds(window_layer);

  text_layer = text_layer_create((GRect) { .origin = { 0, 72 }, .size = { bounds.size.w, 20 } });
  text_layer_set_text(text_layer, "Press a button");
  text_layer_set_text_alignment(text_layer, GTextAlignmentCenter);
  layer_add_child(window_layer, text_layer_get_layer(text_layer));
*/
  Layer *window_layer = window_get_root_layer(window);
  GRect bounds = layer_get_bounds(window_layer);

  button_bitmap = gbitmap_create_with_resource(RESOURCE_ID_BUTTON_IMAGE);
  button_labels = bitmap_layer_create ((GRect) {.origin = {bounds.size.w -16, 0}, .size = {16,136}});

  bitmap_layer_set_bitmap(button_labels, button_bitmap);

  time_layer = text_layer_create((GRect) { .origin = { 0, 50 }, .size = { bounds.size.w -16, 36 } });
  my_font = fonts_get_system_font (FONT_KEY_BITHAM_34_MEDIUM_NUMBERS);
  text_layer_set_font (time_layer, my_font);
  text_layer_set_text (time_layer, "00:00.0");

  layer_add_child(window_layer, text_layer_get_layer(time_layer));
  layer_add_child(window_layer, bitmap_layer_get_layer(button_labels));
  
}

static void window_unload(Window *window) {
  text_layer_destroy(text_layer);
  bitmap_layer_destroy(button_labels);
}

static void init(void) {
  window = window_create();
  window_set_click_config_provider(window, click_config_provider);
  window_set_window_handlers(window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });

  const bool animated = true;
  window_stack_push(window, animated);
}

static void deinit(void) {
  window_destroy(window);
}

int main(void) {
  init();

  APP_LOG(APP_LOG_LEVEL_DEBUG, "Done initializing, pushed window: %p", window);

  app_event_loop();
  deinit();
}
